version: '2'
services:
  mysql:
    build: ./mysql
    ports: 
      - '3306:3306'
    environment:
      MYSQL_USER: pruebas
      MYSQL_PASSWORD: pruebas
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: dbase
    volumes:
      - db:/var/lib/mysql
  php:
    build: ./apache_php
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

volumes:
  db:
